---
openapi: 3.0.0
info:
  title: DriverLicenseService
  description: Provide Driver License details
  version: 1.0.0
paths:
  /drivers/driver:
    get:
      description: Get a Driver details based on Driver Id
      parameters:
      - name: Id
        in: query
        required: true
        schema:
          type: number
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Driver'
              examples:
                Satya:
                  value: |-
                    [
                    {"DriverId": 1, "FirstName": Satya, "LastName": Jayanti, "License": "GPTE101", "Valid": true}
                    ]
    put:
      description: Update Driver Information based on Driver Id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Driver'
        required: true
      responses:
        201: {}
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Driver'
        required: true
      responses:
        201: {}
    delete:
      description: Delete a Driver based on Id
      parameters:
      - name: Id
        in: query
        required: true
        schema:
          type: number
      responses:
        200: {}
  /drivers:
    get:
      description: Get a list of all drivers.
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Driver'
              examples:
                GPTE_List:
                  value: |-
                    [
                        {"DriverId": 1, "FirstName": "Satya", "LastName": "Jayanti", "License": "GPTE101", "Valid": true},
                        {"DriverId": 2, "FirstName": "Jeff", "LastName": "Bride", "License": "GPTE102", "Valid": true}
                        {"DriverId": 3, "FirstName": "Jeffrey", "LastName": "Delong", "License": "GPTE103", "Valid": true}
                        {"DriverId": 4, "FirstName": "Nandan", "LastName": "Joshi", "License": "GPTE104", "Valid": false}
                        {"DriverId": 5, "FirstName": "Bernard", "LastName": "Tison", "License": "GPTE105", "Valid": true}
                        {"DriverId": 6, "FirstName": "Hong Hua", "LastName": "Chin", "License": "GPTE106", "Valid": false}
                        {"DriverId": 7, "FirstName": "Chad", "LastName": "Darby", "License": "GPTE107", "Valid": true}
                        {"DriverId": 8, "FirstName": "Jatinder", "LastName": "Singh", "License": "GPTE108", "Valid": true}
                    ]
  /drivers/driver/{id}/valid:
    get:
      description: Get the Driver's License details
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        200:
          content:
            application/json:
              schema:
                type: boolean
components:
  schemas:
    Driver:
      required:
      - DriverId
      - LastName
      - FirstName
      - License
      - Valid
      properties:
        DriverId:
          type: number
        LastName:
          type: string
        FirstName:
          type: string
        License:
          type: string
        Valid:
          type: boolean
